name: GestionSystem
version: 0.0.1
description: A minimal web app for the developer that doesn’t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  googleapis: any
  googleapis_auth: any
  mock: any
  redstone: any
  redstone_mapper: any
  redstone_mvc: any
  redstone_rethinkdb: any
  shelf: any
  shelf_static: any
  unittest: any
  redstone_mapper_mongo: any
  path: ">=1.3.5 <2.0.0"
transformers:
- redstone_mapper

- $dart2js:
    $exclude:
    - bin
    - '*test*'
    minify: true
